# Generated by Django 6.0.3 on 2026-05-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Categories',
            new_name='categories',
        ),
    ]
