# Generated by Django 6.0.3 on 2026-05-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_category_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
