# Generated by Django 6.0.3 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofiles",
            name="is_agent",
            field=models.BooleanField(default=False),
        ),
    ]
